### ISSUE TITLE
Tribeca with new currencies not working

### ISSUE THREAD

**Issue by Camille92** [michaelgrosner/tribeca#100]
Hi Michael,

I was trying to use Tribeca on the LTC/BTC market on Gdax.

However is doesn't seems to work here is the log I get:

`{"name":"tribeca:gateway:CoinbaseOE","hostname":"a8eded981008","pid":14,"level":40,"msg":"NO EXCHANGE ID PROVIDED FOR ORDER ID: 7225bf30-2948-11e7-a845-a154ee269027 null { message: 'price must be greater than zero (0)' }","time":"2017-04-24T23:47:58.794Z","v":0}`

I think it's not that much missing haha.

Best,
Camille

**Comment by michaelgrosner** [comment]
Can you tell me how much you were trying to buy or sell for?

**Comment by Camille92** [comment]
I did different try:
Size 3 and 0.1
Width 0.3, 0.1, 0.05
Mode Top and Ping pong
And always got the same result. Apart from that everything was working well, the price from the market and what I have in BTC and LTC in my account.

**Comment by michaelgrosner** [comment]
I was able to reproduce the issue and am addressing it in #102 

I'll close this issue.
