### ISSUE TITLE
Missing source

### ISSUE THREAD

**Issue by ambethia** [michaelgrosner/tribeca#107]
As I [pointed out](https://github.com/michaelgrosner/tribeca/commit/e50f9e686a125c595814ab50f084aef608d7da28#commitcomment-21947143)

```
src/service/main.ts(54,27): error TS2307: Cannot find module './promises'.
```

Maybe you forgot to stage a new file?

**Comment by michaelgrosner** [comment]
Ugh. Sorry about that. I won't have a chance to fix until Sunday.

**Comment by michaelgrosner** [comment]
Ok, it should be included in master.
