### ISSUE TITLE
Order list not working

### ISSUE THREAD

**Issue by US-Mining-Rentals** [michaelgrosner/tribeca#110]
I have Tribeca manually installed on an ubuntu 16.04 server.
Everything works fine except for the order list. It is simply not populating.
It is hooked up to GDAX via the coinbase api settings.
I'd like to paste a logfile, but there is alot of secure info there, us passwords, etc.

**Comment by michaelgrosner** [comment]
The order list does much less now than before. It will only show orders when submitting them through the "Submit Order" button on the top right of the UI. It will not show automated orders as those were becoming a serious performance drag on both the trading system and the web view.

**Comment by US-Mining-Rentals** [comment]
I'd like to contribute css to make that part of the interface take up less
real estate, if that's ok with you. How do I get started?
