### ISSUE TITLE
Bot does not provide Order List although orders are open and filling

### ISSUE THREAD

**Issue by renkcub** [michaelgrosner/tribeca#111]
This is showing blank on both GDAX and Bitfinex.

I see other related issues, possibly.

Not sure the problem. Any fixes or anyone else experiencing this?

https://github.com/michaelgrosner/tribeca/issues/78
https://github.com/michaelgrosner/tribeca/issues/35

**Comment by joral** [comment]
Yes, I am having the same issue.  Don't know what's going on though.

**Comment by michaelgrosner** [comment]
The app no longer shows automated orders from market making, the order list only shows orders placed manually via the web UI.

The reason I took away this functionality was that it was exerting a huge amount of pressure on the trading engine garbage collector and making the web UI super slow, without any benefit. I could re-add it via configuration if you would like to see those orders?

**Comment by ericbouchard** [comment]
It could be useful when trading in markets with low liquidity.

**Comment by ericscheier** [comment]
+1 for re-adding via config

Also very useful when backtesting, paper trading, and testing on the null exchange

**Comment by ericscheier** [comment]
@michaelgrosner could you provide any quick guidance on how to re-enable this feature? I'm happy to submit a pull request but I figure there's no need to re-invent the wheel here.

**Comment by michaelgrosner** [comment]
This feature has been added.
