### ISSUE TITLE
Bot sells at a loss?

### ISSUE THREAD

**Issue by aashay** [michaelgrosner/tribeca#113]
Should this be possible? Testing with settings: 
* Mode: Top
* fv: wBBO
* apMode: Off
* Width: .02
* Size: 1 (LTC)
* tbp: 1
* pDiv: 1
trds/sec: 300/60
![screenshot 2017-05-07 18 28 14](https://cloud.githubusercontent.com/assets/396236/25787118/8430363c-3353-11e7-86ed-7379e5caf5c7.png)

Notice that original size was set to 0.1, as soon as it was increased and LTC prices dropped the bot started working with the new numbers, but for some reason sold at 28.72 (a price lower than any of those buy prices). 

Does tribeca keep track of all buy fill prices in mongo and sell accordingly? Or is this just draining my cash supply...?

**Comment by Camille92** [comment]
I don't think you understand the way Tribeca is made to make money.

You should read more about market making and the strategies offered by the bot.

To fix your current problem I advise you to chose a wider width setting.

**Comment by aashay** [comment]
@Camille92  - My apologies, I'm new at this, just trying to learn. I've read the wiki about Tribeca's market-making strategies, and while it's clear what each setting does,  it's not immediately obvious how to use them in conjunction (for example, others have commented that a beginner's guide might come in handy).  

A wider width can slow trading down considerably.

**Comment by renkcub** [comment]
If you don't want to sell at a loss, use Ping Pong.

However, I'm having troubles also. The bot only seems to place either a bid or an ask, not both. Why is that?

**Comment by aashay** [comment]
@renkcub I've noticed the same pattern using Ping Pong.  I'm probably just not fully understanding what the strategy means, but I doubt I'm alone.  Would love some more clarity in the docs! 

Closing this issue.

**Comment by lirenz** [comment]
You'll never fix that problem - or at least that's where the risk comes from. Imagine a market where trades only go in 1 direction (say, everyone just wants to buy), then the bot will keep selling until you hit position limits in which case it'll start trying to unwind by only offering to buy (probably at a higher price - i.e. loss). Setting a very wide width gives you more margin for error, but fewer trades. The bot doesn't appear to have predictive abilities features.
