### ISSUE TITLE
Strategy Enhancement

### ISSUE THREAD

**Issue by prismtrader** [michaelgrosner/tribeca#115]
I have a strategy that would make Tribeca consistently profitable but i'm a trader not a programmer. If anyone is interested in coding the changes i would share the strategy with them.

**Comment by michaelgrosner** [comment]
Sure, can you describe it?

**Comment by prismtrader** [comment]
Great. I can only describe it very broadly publicly. But it would involve adding support for 2 new exchanges that aren't supported yet. One for market making and the other for hedging. I can get into the specifics of the strategy and how and why it would work via email aidas153@gmail.com

**Comment by michaelgrosner** [comment]
If you can't describe it publicly then I won't merge add it to the repo.
