### ISSUE TITLE
exitingEvent is not a function

### ISSUE THREAD

**Issue by egasimus** [michaelgrosner/tribeca#116]
When trying to run a freshly compiled checkout of Tribeca:

```
/home/magare/Code/tribeca/tribeca/service/main.js:54                                           
    Promises.timeout(2000, exitingEvent()).then(completed => {                                    
                           ^                                                                   
                                                                                               
TypeError: exitingEvent is not a function                                                      
    at performExit (/home/magare/Code/tribeca/tribeca/service/main.js:54:28)                   
    at process.on.err (/home/magare/Code/tribeca/tribeca/service/main.js:64:5)                 
    at emitOne (events.js:96:13)                                                               
    at process.emit (events.js:191:7)                                                                                                   
    at process._fatalException (bootstrap_node.js:304:26)           
```

Changing `tribeca/service/main.js:52` from

```
let exitingEvent;
```

to:

```
let exitingEvent = () => {};
```

does fix this, but the issue arises again on recompilation, hampering development.

**Comment by michaelgrosner** [comment]
This error is a red-herring - something else is breaking during start-up. I'll accept a PR to make that change but this isn't the real issue you are experiencing.

**Comment by egasimus** [comment]
I think it's happening because of a missing configuration value; providing a `tribeca.json` bypasses it. However (!) for `performExit` to ever be called before `exitingEvent` has been assigned, is not logically correct, and results in a misleading error message, which is why I consider my pull request to be necessary as-is. Your thoughts on this?

**Comment by michaelgrosner** [comment]
Sorry, missed your initial PR. Merged it in.

**Comment by egasimus** [comment]
Cool, thanks! :+1:
