### ISSUE TITLE
linux support

### ISSUE THREAD

**Issue by jrabello** [michaelgrosner/tribeca#118]
Have you plans to add support for Linux users?

**Comment by ctubio** [comment]
you mean beers and chocolates after install?

**Comment by michaelgrosner** [comment]
I run tribeca on ubuntu. Are you noticing something that's not working on your Linux installation?

**Comment by jrabello** [comment]
@michaelgrosner  just thought it was only possible to install using mac/windows, but managed to install it here successfully, thanks!
