### ISSUE TITLE
Docker/Tribeca installation - Web admin doesn't serve anything

### ISSUE THREAD

**Issue by virento** [michaelgrosner/tribeca#12]
I completed the Docker Tribeca installation following the instructions within the README file verbatim and I'm running into an issue.  When I connect to port 3000 I get a blank page (zero content served).  I'm positive that Tribeca is running and listening on port 3000.  I've verified that the same behaviour occurs when connecting locally instead of remotely.  The install is running on an Amazon EC2 micro instance if that makes any difference.  I ensured to allow traffic to/from the EC2 instance on port 3000 within the Amazon EC2 admin interface and disabled local firewall for testing.  I also tried disabling IPv6 system wide in the event that was causing a problem.  Below is some output from Docker to show that Tribeca is running (along with MongoDB):

CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                              NAMES
63586d1f9a38        tribeca:latest      forever main.js        About an hour ago   Up 5 seconds        5000/tcp, 0.0.0.0:3000->3000/tcp   tribeca                       
84a36f5fa86a        mongo:latest        /entrypoint.sh mongo   About an hour ago   Up 34 minutes       0.0.0.0:27017->27017/tcp           tribeca/mongo,tribeca-mongo

Any suggestions?  Also, is there a log file I can look at to find additional info for troubleshooting purposes?

Any help is certainly appreciated :)

**Comment by michaelgrosner** [comment]
Hey, you can check out the logs in the `tribeca/service` folder... they're the files like tribeca.*.log. If the service is still indeed up and running, you should find it logging something. If you want to share the log contents here, please do so (just don't share any API keys/usernames). 

Also, if you are running on OS X/windows, you should not go to localhost, but to whatever `boot2docker ip` says the docker address is. 

I tried your exact setup on AWS a few days ago and it worked fine for me, so I'm a bit stumped about what it could be without seeing some logging.

**Comment by virento** [comment]
The AWS instance is running Ubuntu 14.04 LTS server 64bit and the Docker install from from the default Ubuntu 14.04 repo.

Thanks for pointing me to the logs, was able to make some progress but unfortunately I still have the same problem.  When looking at the logs initially, I noticed it wasn't connecting to the mongoDB instance I have running per the instructions which was due to the URL referencing 'tribeca-mongo' instead of 'localhost'.  I deleted the Tribeca instance/image, made the appropriate change in the DockerFile and redeployed Tribeca.  The error is now gone however I still have the exact same issue (connects to the port and then the port is immediately closed by the server).  Below is a snippet from the logs which illustrates 3 Tribeca instance restarts:

info: 8/7/15 13:06:21,403       [tribeca:config]        EXCHANGE = null
info: 8/7/15 13:06:21,410       [tribeca:config]        MongoDbUrl = mongodb://localhost:27017/tribeca
info: 8/7/15 13:06:21,424       [tribeca:main]  Listening to admins on *:3000...
info: 8/7/15 13:07:32,630       [tribeca:config]        EXCHANGE = null
info: 8/7/15 13:07:32,637       [tribeca:config]        MongoDbUrl = mongodb://localhost:27017/tribeca
info: 8/7/15 13:07:32,651       [tribeca:main]  Listening to admins on *:3000...
info: 8/7/15 13:08:01,369       [tribeca:config]        EXCHANGE = null
info: 8/7/15 13:08:01,377       [tribeca:config]        MongoDbUrl = mongodb://localhost:27017/tribeca
info: 8/7/15 13:08:01,393       [tribeca:main]  Listening to admins on *:3000...

No other information in the logs appears than what you see above.

Any ideas?

**Comment by michaelgrosner** [comment]
Hmm.. I'm trying to reproduce the issue on AWS to no avail. It's also a bit strange that there are absolutely no errors being written to the logs - I would have expected there to be at least something there. 

Is the mongo instance on the localhost of the AWS machine, or in the same container as tribeca? If you are running mongo via a separate docker container (as in the README instructions), it should be pointing to `mongodb://tribeca-mongo:27017/tribeca`. If it's a mongo instance outside of docker, but on the same machine, you should not use localhost but follow the instructions given here: http://stackoverflow.com/a/24326540.

One idea is have you specified the `TRIBECA_MODE`? I can get the code to freeze up if that's not specified in the Dockerfile ENV or tribeca.json files.

I'm going to dig into this a bit more, it seems like any sort of initialization configuration errors can be unreported.

**Comment by virento** [comment]
MongoDB is a Docker instance per the instructions found in the README.  Docker was installed via 'apt-get install docker.io'.  I've noticed that if I don't copy sample-dev-tribeca.json to rootfs/tribeca/tribeca/service/tribeca.json a log isn't generated in the same directory as if it's not running at all even though 'docker ps' shows it is.  Based on the instructions, it appears you are only supposed to copy that file for a non-Docker deployment however maybe I misunderstood.

The TRIBECA_MODE ENV is set to 'dev'.  I left all of the items in Dockerfile as is since the Tribeca installation will be used in dev mode initially.

I've removed and redeployed Tribeca and even the MongoDB instance many of times with the same results unfortunately.  Is there any way to tell Tribeca to log more detail?

**Comment by virento** [comment]
Well, it appears we have resolved the issue.  Docker apparently wasn't linking the containers properly and the resolution was installing the latest version of Docker from Docker's apt repo instead of using the version of Docker found within the standard Ubuntu 14.04 LTS repo.  Is there a minimum Docker version requirement for Tribeca?

**Comment by michaelgrosner** [comment]
Interesting, what version of docker are you using? I believe I would always upgrade it before using, and on my dev machine, I'm using 1.7.1
