### ISSUE TITLE
Display Spread

### ISSUE THREAD

**Issue by maurodelazeri** [michaelgrosner/tribeca#128]
It would be nice to add a field to show the current spread in real time

**Comment by michaelgrosner** [comment]
I agree, in terms of absolute ($) width and a percentage.

**Comment by maurodelazeri** [comment]
I thought absolute, but the percentage is not a bad idea tho

**Comment by maurodelazeri** [comment]
Guys,
Suggestion, now we have the spread on the top of the grid, why not filling it all, with the spread in all levels of price?

![tribeca prod 2017-06-05 10-46-20](https://cloud.githubusercontent.com/assets/1005120/26788753/440a56b0-49dc-11e7-8816-041a56f5c56b.png)

**Comment by michaelgrosner** [comment]
I agree that there is more wasted whitespace now, but personally I don't feel that non top-of-book spread is that useful.
