### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by amexperts** [michaelgrosner/tribeca#135]
Was wondering whether someone would be willing to help me set this up on digitalocean?

**Comment by shanehull** [comment]
@amexperts how did you go with this?

I've got it installed on a droplet with a nginx reverse proxy in front of it, however I'm getting server error 500. It's like it's not running at all.

Config looks like:

`    "TRIBECA_MODE": "prod",
    "EXCHANGE": "bitfinex",
    "TradedPair": "BTC/ETH",
    "MongoDbUrl": "mongodb://localhost:27017/tribeca",
    "WebClientUsername": "admin",
    "WebClientPassword": "Tribeca4all",
    "WebClientListenPort": "80",`

nginx config looks like:

`server {
    listen 80;
    listen [::]:80;
    server_name tribeca.example.com;
    return 301 https://$server_name$request_uri;
}

upstream websocket {
    server localhost:3000;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    root /var/www/html;
`
