### ISSUE TITLE
GDAX aka Coinbase not Working.... Confirmed that Bitfinex works

### ISSUE THREAD

**Issue by refuuj** [michaelgrosner/tribeca#141]
I'm having trouble figuring out why I can't get this up and running with GDAX. I have created 3 different API keys and no matter what I see from the logs that I get an "Invalid API key error" This happens in both dev and  prod mode. Obviously I would like things working in dev mode as well as prod so that I can test before setting this thing out in the wild.

**Comment by RootPhish** [comment]
Are you sure you are using the correct URLs? I use these (for prod):
CoinbaseRestUrl=https://api.gdax.com
CoinbaseWebsocketUrl=wss://ws-feed.gdax.com

**Comment by refuuj** [comment]
@RootPhish i figured it out. i needed to go to https://public.sandbox.gdax.com login and create separate sandbox keys for dev.

prod is working for me as well
