### ISSUE TITLE
How to run tests

### ISSUE THREAD

**Issue by bappelt** [michaelgrosner/tribeca#15]
Hello, I was just wanting to know the process you use for running the tests. Sorry about opening an issue for this question, but I could not find a better way to contact you.

**Comment by michaelgrosner** [comment]
Hey, no problem. Uhh... there's no good way to do it. I usually would compile by "hand" via `tsc` then would run via `mocha`. I should spend some time writing a test suite for the application...

**Comment by bappelt** [comment]
Thanks, I thought that might be the case, but I'm a total newbie with typescript and fairly new with node as well so I wanted to make sure I wasn't missing something obvious.
