### ISSUE TITLE
OKCoin unsuccessful message

### ISSUE THREAD

**Issue by arancauchi** [michaelgrosner/tribeca#17]
OKCoin is producing unsuccessful error message, with error code 10015. Unable to compute EWMA. 

See attached screenshot
![capture](https://cloud.githubusercontent.com/assets/3953859/9291541/28e80cda-440a-11e5-8e7d-da7a6c9c0248.PNG)

**Comment by michaelgrosner** [comment]
Hey, I noticed that today while doing some testing with OkCoin. From their documentation, 10015 means "Channel subscription temporally not available" (https://www.okcoin.com/about/ws_request.do), so I assumed it meant something their side was down. I just emailed OkCoin to see what's going on and directed them to this issue, hopefully we'll hear back soon.

**Comment by michaelgrosner** [comment]
On a related issue, I should not say that OkCoin is connected when one of these logons fails

**Comment by arancauchi** [comment]
Interesting, connecting via the old OKCoin-ask-sorting branch seems to work perfectly (sending and making orders). Is there a difference in connection technologies between the old branch and the new master?

**Comment by michaelgrosner** [comment]
Ugh, I see the error, I introduced it when adding support for currency pairs other than BTC/USD. Rookie mistake. Link to the bad line, I accidentally added a "_" https://github.com/michaelgrosner/tribeca/commit/a2ec71e4e503230522d058123dc80166cfbb9dfe#diff-1af7ffe54f6edc114300eba07bcd1810R475 -- I'll fix this pronto.

**Comment by michaelgrosner** [comment]
I now noticed that in certain places, they use "btc_usd" in the REST API and "btcusd" in the websocket interface. Slightly maddening..

**Comment by michaelgrosner** [comment]
Fixed in 2e0545ef232b800bba81bbe819a491a8d8777c42
