### ISSUE TITLE
I cannot Launch the App

### ISSUE THREAD

**Issue by AoverK** [michaelgrosner/tribeca#193]
I get the following error when trying to run the program.

{"name":"tribeca:main","hostname":"","pid":8120,"level":50,"err":{"message":"Config does not have property TradedPair","name":"Error","stack":"Error: Config does not have property TradedPair\n    at ConfigProvider.Fetch (F:\\Development\\tribeca-master\\tribeca\\service\\config.js:34:23)\n    at ConfigProvider.GetString (F:\\Development\\tribeca-master\\tribeca\\service\\config.js:25:25)\n    at Object.<anonymous> (F:\\Development\\tribeca-master\\tribeca\\service\\main.js:86:39)\n    at Module._compile (module.js:624:30)\n    at Object.Module._extensions..js (module.js:635:10)\n    at Module.load (module.js:545:32)\n    at tryModuleLoad (module.js:508:12)\n    at Function.Module._load (module.js:500:3)\n    at Function.Module.runMain (module.js:665:10)\n    at startup (bootstrap_node.js:187:16)"},"msg":"Unhandled exception!","time":"2017-12-10T02:45:27.306Z","v":0}

**Comment by marqui678** [comment]
How did you fix it?
