### ISSUE TITLE
btce upgrade info

### ISSUE THREAD

**Issue by Pascal66** [michaelgrosner/tribeca#23]
26/08/15	BTC-e code API update
(source btce)

**Comment by Pascal66** [comment]
Hi there, is btce branch working ? Ty for you work

**Comment by michaelgrosner** [comment]
Hey, I tried for a while to get BTC-E working but their API is total garbage and wasn't going to work well with tribeca, so I gave it up. The branch is still there.

**Comment by michaelgrosner** [comment]
Not going to write to BTC-E.
