### ISSUE TITLE
Box too short on UI

### ISSUE THREAD

**Issue by Pascal66** [michaelgrosner/tribeca#25]
Cant read the 't'/'text' box content bellow 'market data and quote' in my screen

**Comment by ctubio** [comment]
im sorry no PR, but a screenshot:
![issue25](https://cloud.githubusercontent.com/assets/1634027/14232706/18ab462a-f9b3-11e5-8aa4-3728ae8ee541.png)

that was using:

|OS Type|OS Version|Browser Type|Browser Type|Javascript Enabled|Cookies Enabled|Color Depth|Screen Resolution|Browser Window Size|Flash Version|User Agent|
|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|
|Windows|7|Chrome|49.0.2623.87|Yes|Yes|24|1600 x 900|1264 x 670|21.0.-1|"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML| like Gecko) Chrome/49.0.2623.87 Safari/537.36"|
