### ISSUE TITLE
Fails to startup

### ISSUE THREAD

**Issue by jhu104** [michaelgrosner/tribeca#40]
After I fixed issue #36, the below error is logged when I run the container:

info: 1/9/16 16:19:52,904	[tribeca:config]	MongoDbUrl = mongodb://tribeca-mongo:27017/tribeca
info: 1/9/16 16:19:52,916	[tribeca:main]	Listening to admins on *:3000
info: 1/9/16 16:19:52,958	[tribeca:config]	TRIBECA_MODE = dev
error: Terminating! uncaughtException [TypeError: undefined is not a function] TypeError: undefined is not a function
    at new Publisher (/tribeca/tribeca/common/messaging.js:41:34)
    at getPublisher (/tribeca/tribeca/service/main.js:130:33)
    at /tribeca/tribeca/service/main.js:190:9
    at /tribeca/node_modules/q/q.js:1229:26
    at _fulfilled (/tribeca/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/tribeca/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/tribeca/node_modules/q/q.js:796:13)
    at /tribeca/node_modules/q/q.js:556:49
    at runSingle (/tribeca/node_modules/q/q.js:137:13)
    at flush (/tribeca/node_modules/q/q.js:125:13)

**Comment by jhu104** [comment]
Debugging through the code, I see a very weird behavior.

When I use node console:
**var test = require('./messaging.js');**

it will import the variables in Topics, including *Topics.ProductAdvertisement* thats needed at line 190 in main.js (line 270 in main.ts)

but when I put breakpoint in main.js at line 190 then use repl:
Messaging Object's Topics only contains functions and when I try to reimport it, Topics still only contains a function

**Comment by WaleedAshraf** [comment]
same issue :/

**Comment by jhu104** [comment]
@WaleedAshraf, I got this fixed yesterday. Please update your local code.
