### ISSUE TITLE
Recommended Upgrade Procedure

### ISSUE THREAD

**Issue by virento** [michaelgrosner/tribeca#44]
Hello, I was curious if there was a recommended upgrade procedure to upgrade an existing Tribeca installation.  If so, can you point me to any documentation that describes it or outline it here?

Thank you!

**Comment by virento** [comment]
I'm using the Docker installation method BTW

**Comment by gagarine** [comment]
Why not just recreate a new Docker image of tribeca?

**Comment by michaelgrosner** [comment]
Yeah, the preferred way of upgrading tribeca is via rebuilding the image.

**Comment by virento** [comment]
Sounds good, thank you!
