### ISSUE TITLE
Error in Tribeca build - Task "ts:service" failed error during 'grunt compile'

### ISSUE THREAD

**Issue by virento** [michaelgrosner/tribeca#50]
Hello,
     I'm attempting to reinstall Tribeca with changes that have been implemented since January and I'm running into a problem on step 9 of the Tribeca build.  I'm using the same Dockerfile I have previously with success and modified it to match the latest Dockerfile on the repo.  Below is the error message I receive before it stops:

> Step 9 : RUN grunt compile
>  ---> Running in 2df7799d5d1a
> Running "ts:service" (ts) task
> Compiling...
> ### Fast Compile >>src/service/active-state.ts
> ### Fast Compile >>src/service/backtest.ts
> ### Fast Compile >>src/service/broker.ts
> ### Fast Compile >>src/service/config.ts
> ### Fast Compile >>src/service/fair-value.ts
> ### Fast Compile >>src/service/gateways/bitfinex.ts
> ### Fast Compile >>src/service/gateways/coinbase-api.ts
> ### Fast Compile >>src/service/gateways/coinbase.ts
> ### Fast Compile >>src/service/gateways/hitbtc.ts
> ### Fast Compile >>src/service/gateways/nullgw.ts
> ### Fast Compile >>src/service/gateways/okcoin.ts
> ### Fast Compile >>src/service/interfaces.ts
> ### Fast Compile >>src/service/main.ts
> ### Fast Compile >>src/service/market-filtration.ts
> ### Fast Compile >>src/service/markettrades.ts
> ### Fast Compile >>src/service/messages.ts
> ### Fast Compile >>src/service/persister.ts
> ### Fast Compile >>src/service/position-management.ts
> ### Fast Compile >>src/service/quote-sender.ts
> ### Fast Compile >>src/service/quoter.ts
> ### Fast Compile >>src/service/quoting-engine.ts
> ### Fast Compile >>src/service/quoting-parameters.ts
> ### Fast Compile >>src/service/quoting-styles/helpers.ts
> ### Fast Compile >>src/service/quoting-styles/mid-market.ts
> ### Fast Compile >>src/service/quoting-styles/style-registry.ts
> ### Fast Compile >>src/service/quoting-styles/top-join.ts
> ### Fast Compile >>src/service/safety.ts
> ### Fast Compile >>src/service/statistics.ts
> ### Fast Compile >>src/service/utils.ts
> ### Fast Compile >>src/service/web.ts
> ### Fast Compile >>src/common/messaging.ts
> ### Fast Compile >>src/common/models.ts
> Using tsc v1.4.1
> /tribeca/src/service/gateways/coinbase.ts(471,33): error TS1005: '=' expected.
> /tribeca/src/service/gateways/coinbase.ts(471,36): error TS1005: ',' expected.
> /tribeca/src/service/gateways/coinbase.ts(471,40): error TS1005: ',' expected.
> /tribeca/typings/node/node.d.ts(128,29): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(128,32): error TS1005: ',' expected.
> /tribeca/typings/node/node.d.ts(135,24): error TS1005: ',' expected.
> /tribeca/typings/node/node.d.ts(135,33): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(143,22): error TS1005: ',' expected.
> /tribeca/typings/node/node.d.ts(143,41): error TS1109: Expression expected.
> /tribeca/typings/node/node.d.ts(143,50): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(155,16): error TS1005: ',' expected.
> /tribeca/typings/node/node.d.ts(155,40): error TS1109: Expression expected.
> /tribeca/typings/node/node.d.ts(155,49): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(159,17): error TS1005: ',' expected.
> /tribeca/typings/node/node.d.ts(159,31): error TS1005: ',' expected.
> /tribeca/typings/node/node.d.ts(159,40): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(160,1): error TS1128: Declaration or statement expected.
> /tribeca/typings/node/node.d.ts(417,5): error TS1128: Declaration or statement expected.
> /tribeca/typings/node/node.d.ts(417,23): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(417,26): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(417,47): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(417,50): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(457,5): error TS1128: Declaration or statement expected.
> /tribeca/typings/node/node.d.ts(457,12): error TS1109: Expression expected.
> /tribeca/typings/node/node.d.ts(457,17): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(457,24): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(457,29): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(458,5): error TS1128: Declaration or statement expected.
> /tribeca/typings/node/node.d.ts(458,12): error TS1109: Expression expected.
> /tribeca/typings/node/node.d.ts(458,17): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(458,21): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(458,26): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(459,5): error TS1128: Declaration or statement expected.
> /tribeca/typings/node/node.d.ts(459,12): error TS1109: Expression expected.
> /tribeca/typings/node/node.d.ts(459,17): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(459,24): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(459,29): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(620,5): error TS1128: Declaration or statement expected.
> /tribeca/typings/node/node.d.ts(620,12): error TS1109: Expression expected.
> /tribeca/typings/node/node.d.ts(620,17): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(620,23): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(620,28): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(621,5): error TS1128: Declaration or statement expected.
> /tribeca/typings/node/node.d.ts(621,12): error TS1109: Expression expected.
> /tribeca/typings/node/node.d.ts(621,17): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(621,24): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(621,29): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(667,5): error TS1128: Declaration or statement expected.
> /tribeca/typings/node/node.d.ts(667,12): error TS1109: Expression expected.
> /tribeca/typings/node/node.d.ts(667,17): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(667,24): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(667,29): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(774,5): error TS1128: Declaration or statement expected.
> /tribeca/typings/node/node.d.ts(774,12): error TS1109: Expression expected.
> /tribeca/typings/node/node.d.ts(774,17): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(774,21): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(774,26): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(775,5): error TS1128: Declaration or statement expected.
> /tribeca/typings/node/node.d.ts(775,12): error TS1109: Expression expected.
> /tribeca/typings/node/node.d.ts(775,17): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(775,24): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(1778,5): error TS1128: Declaration or statement expected.
> /tribeca/typings/node/node.d.ts(1778,12): error TS1109: Expression expected.
> /tribeca/typings/node/node.d.ts(1778,17): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(1778,24): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(1778,29): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(1936,5): error TS1128: Declaration or statement expected.
> /tribeca/typings/node/node.d.ts(1936,12): error TS1109: Expression expected.
> /tribeca/typings/node/node.d.ts(1936,17): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(1936,21): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(1936,26): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(1952,5): error TS1128: Declaration or statement expected.
> /tribeca/typings/node/node.d.ts(1952,12): error TS1109: Expression expected.
> /tribeca/typings/node/node.d.ts(1952,17): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(1952,24): error TS1005: ';' expected.
> /tribeca/typings/node/node.d.ts(1952,29): error TS1005: ';' expected.
> 
> >> 158 syntax errors  
> >> Error: tsc return code: 1
> Warning: Task "ts:service" failed. Use --force to continue.
> 
> Aborted due to warnings.
> The command '/bin/sh -c grunt compile' returned a non-zero code: 3

Any ideas?

**Comment by virento** [comment]
FYI, this is a Ubuntu 14.04 LTS 64bit server w/ 2x 2GHz CPUs and 4GB of memory using the latest version of Docker offered directly from the Docker package repo.  As I mentioned before, this exact same setup was working previously however I destroyed the Docker/Mongo Docker instances/images and started over to get the latest code.

**Comment by michaelgrosner** [comment]
Hi @virento - I've been looking at this issue the past couple of days. I think something in the typings file was upgraded and doesn't play well with other type definitions. I may fix this at the same time I fix #43

**Comment by virento** [comment]
Thanks Michael, I appreciate your reply and your efforts to resolve the issue.  Please let me know if you need any additional info from me or if you would like me to test anything to help with this.

**Comment by michaelgrosner** [comment]
I didn't mean to close this issue... I referenced it in the latest pull request I just merged. @virento - it should fix your issue.

**Comment by ctubio** [comment]
for me is fixed now, thanks!

**Comment by virento** [comment]
Looking good here, thanks Michael!
